# Numpy

## 1. Numpy arrays

fl_sp bevat de oppervlaktes in vierkante meters van 5 winkels.   
turnover bevat de omzet in Britse Ponden (GBP) van dezelfde 5 winkels (in dezelfde volgorde).

- Importeer Numpy.
- Zet de lists om in de Numpy arrays np_fl en np_to.
- Print de types van de arrays.
- Maak een nieuwe array to_eur aan waarin de omzetten worden omgezet in Euro bedragen. 
    - Zoek de wisselkoers op op het Internet.  
- Print to_eur.
- Bereken de EUR omzet per vierkante meter per winkel in de nieuwe array to_sqm.
- Print de eerste 3 regels van to_sqm
- Als de omzet per vierkante meter hoger is dan 230 dan wordt dit als 'goed' gezien. Print de elementen die hoger zijn dan deze grenswaarde.
- Print de hoogste omzet per vierkante meter.

In [1]:
fl_sp = [18526, 18569, 12288, 17092, 11307]
turnover = [3410865, 4034051,2297810, 2398990, 2288235]

#Import:
import numpy as np

#Convert to arrays
np_fl = np.array(fl_sp)
np_to = np.array(turnover)

#Print types
print (type(np_fl), type(np_to))

#Convert to EUR and print
to_eur = np_to *1.14
print (to_eur)


#Calculate EUR turnover per sqm and print first 3 items
to_sqm = to_eur / fl_sp
print (to_sqm[:3])

#Print to per sqm > 230
print (to_sqm[to_sqm>230])

# Print the highest turnover
print (max(to_sqm))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[3888386.1  4598818.14 2619503.4  2734848.6  2608587.9 ]
[209.88805463 247.66105552 213.17573242]
[247.66105552 230.70557177]
247.66105552264526

## 2 Numpy 2D arrays
De list met lists fl_sp_to bevat de oppervlaktes in vierkante meters en de omzetten in GBP van 5 winkels.
- Zet fl_sp_to om in een 2D Numpy array.
- Laat zien hoeveel rijen en kolommen fl_sp bevat.
- Print de tweede kolom van de laatste 4 regels.
- Print de tweede rij tot en met de vierde rij.
- Converteer de vloeroppervlaktes naar feet (i.p.v. vierkante meters) en de GBP bedragen naar EUR. Zoek de juiste omrekenfactoren op op het internet. De nieuwe array krijgt als naam conv.
- Print conv.
- Elke winkelmanager krijgt een bonus. De bonus percentages staan in de bonus list. Het bonusbedrag is het  bonuspercentage maal de omzet. Maak de array bon_amount met daarin de vloeroppervlaktes en de bonus bedragen. Zet hiervoor eerst de bonus list om in een array. Gebruik deze array bij het maken van bon_amount.
- Print bon_amount.

In [10]:
fl_sp_to = [[18526, 3410865],
            [18569, 4034051],
            [12288, 2297810], 
            [17092, 2398990], 
            [11307, 2288235]]
#Convert into a 2D array
np_fl_to = np.array(fl_sp_to)

#print shape
print (np_fl_to.shape)

#print second column of last 4 rows
print (np_fl_to[-4:,1])
print ()
#print second row up to and including the 4th row
print (np_fl_to[1:4,:])
print ()

#Convert to feet and EUR
conv = np_fl_to * [3.28084**2, 1.14]
print (conv)
print()

#Bonus table
bonus = [[1, 0.010],
         [1, 0.008],
         [1, 0.007], 
         [1, 0.011], 
         [1, 0.005]]
# bonus amount
np_bonus = np.array(bonus)
bon_amount = conv * np_bonus
print (bon_amount)

(5, 2)
[4034051 2297810 2398990 2288235]

[[  18569 4034051]
 [  12288 2297810]
 [  17092 2398990]]

[[ 199412.21714235 3888386.1       ]
 [ 199875.06531989 4598818.14      ]
 [ 132266.93966561 2619503.4       ]
 [ 183976.76861692 2734848.6       ]
 [ 121707.54287102 2608587.9       ]]

[[199412.21714235  38883.861     ]
 [199875.06531989  36790.54512   ]
 [132266.93966561  18336.5238    ]
 [183976.76861692  30083.3346    ]
 [121707.54287102  13042.9395    ]]

## 3 Integratie opdracht

In onderstaande cel worden winkelgegevens geimporteerd uit een csv-bestand met behulp van Pandas. Dit is iets waar we de komende lessen veel dieper op in gaan. Het resultaat is dat er een 2D numpy array st_to beschikbaar is voor deze opdracht.

In st_to vind je het aantal medewerkers (staff members) en de omzet (turnover) per winkel. We verwachten dat er een verband is tussen het aantal medewerkers en de omzet. Dat gaan we nu onderzoeken.

- Bereken het gemiddelde, de mediaan en de standaarddeviatie van beide kolommen.
- Wat valt je op aan deze waardes?
- Print de array. Zijn er waardes die sterk afwijken? Welke zijn dat?
- Print de regels uit st_to die hetzelfde aantal medewerkers hebben als het mediane aantal medewerkers.
- Print de correlatiecoefficient voor beide kolommen.
- Welke opties zijn er om de datakwaliteit te verhogen?

In [24]:
#Don't remove this:
import pandas as pd
import numpy as np
storedata = pd.read_csv('storedata.csv', encoding = "ISO-8859-1")
st_to = storedata[['Staff', 'Profit']].values

# Start coding here:
# Staff
staff_median =  np.median(st_to[:,0])
staff_mean =  np.mean(st_to[:,0])
staff_deviation = np.std(st_to[:,0])
print (staff_median)
print (staff_mean)
print (staff_deviation)
print()

# Turnover
turnover_median =  np.median(st_to[:,1])
turnover_mean =  np.mean(st_to[:,1])
turnover_deviation =  np.std(st_to[:,1])
print (turnover_median)
print (turnover_mean)
print (turnover_deviation)
print()

#Staff median and mean are not close and a high stdev. The data needs further investigation. First step: print the array
print (st_to)
print ()

st_to2 = st_to[ np.logical_and(st_to[:,0] <100 , st_to[:,0] > 0)  ]


#print the lines that have a staff number that is the same as the median:
print (st_to[st_to[:,0]==staff_median,:])





staff_median =  np.median(st_to2[:,0])
staff_mean =  np.mean(st_to2[:,0])
staff_deviation = np.std(st_to2[:,0])
print (staff_median)
print (staff_mean)
print (staff_deviation)
print()

# Turnover
turnover_median =  np.median(st_to2[:,1])
turnover_mean =  np.mean(st_to2[:,1])
turnover_deviation =  np.std(st_to2[:,1])
print (turnover_median)
print (turnover_mean)
print (turnover_deviation)
print()
print (np.corrcoef(  [st_to2[:,0],st_to2[:,1]]  ))

7.0
13.352941176470589
56.38399457550571

3018400.5
2990980.9485294116
713958.0028210005

[[      9 3410865]
 [      8 4034051]
 [     -2 2297810]
 [      7 2398990]
 [      7 2288235]
 [      7 3058134]
 [      8 2793160]
 [      9 3345936]
 [      9 3117205]
 [      7 3153278]
 [      9 3056804]
 [      8 1801619]
 [      8 3797953]
 [      8 3138911]
 [      5 2724068]
 [      6 2382751]
 [      8 3321899]
 [      6 2803867]
 [      9 3640627]
 [      9 3075352]
 [      6 3491993]
 [      7 3252148]
 [      7 3041618]
 [      6 3737466]
 [      9 4217291]
 [      5 2008363]
 [      7 3516397]
 [      6 3957233]
 [      5 2942839]
 [      9 2242288]
 [      6 2616387]
 [      7 2493975]
 [      6 2203994]
 [      8 2458785]
 [      8 4253984]
 [      9 4185306]
 [      9 4160531]
 [      7 3100521]
 [      6 3246954]
 [      5 2085733]
 [      9 3741911]
 [      9 2506748]
 [      7 2393869]
 [      8 4137224]
 [      9 3572475]
 [      9 3121837]
 [      5 2799074]
 [      5 2707402]
 [      5 4176642]
 [      7 1829621]
 [      9 2681110]
 [      9 2411437]
 [      7 4300537]
 [    300 3758014]
 [      5 2234201]
 [      8 2342229]
 [      7 2104028]
 [      7 2406120]
 [      6 2839607]
 [      7 2831103]
 [      5 3032277]
 [      7 3625088]
 [      5 2196757]
 [      6 3336417]
 [      6 2779994]
 [      8 3175101]
 [      5 4587304]
 [      8 3029751]
 [      6 1512452]
 [      7 3418735]
 [      6 2526616]
 [      5 2333940]
 [      9 3197934]
 [      5 3135133]
 [      9 3822904]
 [      5 2538362]
 [      7 1855427]
 [      5 2260838]
 [      7 3524409]
 [      8 3709026]
 [      8 3337861]
 [      5 2407898]
 [      6 3260276]
 [      5 1792809]
 [      6 2804353]
 [      6 2869330]
 [      5 2422936]
 [      8 4237135]
 [      7 3007050]
 [      9 4018966]
 [      6 2553461]
 [      7 3817558]
 [      8 2405770]
 [      7 1764019]
 [      6 4793593]
 [      9 2896362]
 [      8 3192066]
 [      5 3092180]
 [      5 2419983]
 [      5 2701564]
 [      9 3606536]
 [      8 3304795]
 [      6 3663843]
 [      6 3965957]
 [      6 2651301]
 [      5 3487542]
 [      7 2004312]
 [      9 3102538]
 [      7 2291029]
 [    600 3895318]
 [      9 3741407]
 [      5 2604575]
 [      5 1648919]
 [      9 1665527]
 [      7 3654694]
 [      5 3598894]
 [      6 2172265]
 [      5 2397407]
 [      6 2329927]
 [      6 3444876]
 [      5 2564358]
 [      9 2534145]
 [      6 2956061]
 [      5 2467943]
 [      6 3891535]
 [      7 3498966]
 [      7 2872001]
 [      6 3501093]
 [      9 3774401]
 [      9 3584813]
 [      5 2561019]
 [      7 2581954]
 [      6 2589339]
 [      7 2583755]
 [      6  950924]
 [      9 3485295]]

[[      7 2398990]
 [      7 2288235]
 [      7 3058134]
 [      7 3153278]
 [      7 3252148]
 [      7 3041618]
 [      7 3516397]
 [      7 2493975]
 [      7 3100521]
 [      7 2393869]
 [      7 1829621]
 [      7 4300537]
 [      7 2104028]
 [      7 2406120]
 [      7 2831103]
 [      7 3625088]
 [      7 3418735]
 [      7 1855427]
 [      7 3524409]
 [      7 3007050]
 [      7 3817558]
 [      7 1764019]
 [      7 2004312]
 [      7 2291029]
 [      7 3654694]
 [      7 3498966]
 [      7 2872001]
 [      7 2581954]
 [      7 2583755]]
7.0
6.902255639097745
1.434613262466279

3007050.0
2983626.067669173
712035.3878640195

[[1.         0.29000514]
 [0.29000514 1.        ]]